"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from speakeasy_client_sdk_python import utils


class BillingAddOn(str, Enum, metaclass=utils.OpenEnumMeta):
    WEBHOOKS = "webhooks"
    SDK_TESTING = "sdk_testing"
    CUSTOM_CODE_REGIONS = "custom_code_regions"
    SNIPPET_AI = "snippet_ai"
