"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from .tag import Tag, TagTypedDict
from speakeasy_client_sdk_python.types import BaseModel
from typing import List, TypedDict


class GetTagsResponseTypedDict(TypedDict):
    items: List[TagTypedDict]
    

class GetTagsResponse(BaseModel):
    items: List[Tag]
    
