"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workflowdocument import WorkflowDocument, WorkflowDocumentTypedDict
import pydantic
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GithubConfigureCodeSamplesResponseTypedDict(TypedDict):
    r"""A response to configure GitHub code samples"""

    code_sample_overlay_registry_url: str
    r"""The URL of the code sample overlay registry"""
    source: WorkflowDocumentTypedDict
    r"""A document referenced by a workflow"""
    gh_action_id: NotRequired[str]
    r"""The ID of the GitHub action that was dispatched"""


class GithubConfigureCodeSamplesResponse(BaseModel):
    r"""A response to configure GitHub code samples"""

    code_sample_overlay_registry_url: Annotated[
        str, pydantic.Field(alias="codeSampleOverlayRegistryURL")
    ]
    r"""The URL of the code sample overlay registry"""

    source: WorkflowDocument
    r"""A document referenced by a workflow"""

    gh_action_id: Annotated[Optional[str], pydantic.Field(alias="ghActionID")] = None
    r"""The ID of the GitHub action that was dispatched"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ghActionID"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GithubConfigureCodeSamplesResponse.model_rebuild()
except NameError:
    pass
