"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_client_sdk_python.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class GithubConfigureMintlifyRepoRequestTypedDict(TypedDict):
    r"""A request to configure a GitHub repository for mintlify"""
    
    input: str
    r"""The input OpenAPI document"""
    org: str
    r"""The GitHub organization name"""
    overlays: List[str]
    r"""The overlays to apply"""
    repo: str
    r"""The GitHub repository name"""
    subdirectory: NotRequired[str]
    r"""The subdirectory (location of mint.json)"""
    

class GithubConfigureMintlifyRepoRequest(BaseModel):
    r"""A request to configure a GitHub repository for mintlify"""
    
    input: str
    r"""The input OpenAPI document"""
    org: str
    r"""The GitHub organization name"""
    overlays: List[str]
    r"""The overlays to apply"""
    repo: str
    r"""The GitHub repository name"""
    subdirectory: Optional[str] = None
    r"""The subdirectory (location of mint.json)"""
    
