"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GithubMissingPublishingSecretsResponseTypedDict(TypedDict):
    r"""A valid response containing MISSING publishing secret keys for a github target"""

    missing_secrets: NotRequired[List[str]]


class GithubMissingPublishingSecretsResponse(BaseModel):
    r"""A valid response containing MISSING publishing secret keys for a github target"""

    missing_secrets: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["missing_secrets"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
