"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from speakeasy_client_sdk_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PullRequestMetadataTypedDict(TypedDict):
    r"""This can only be populated when the github app is installed for a repo"""

    base_branch: NotRequired[str]
    can_merge: NotRequired[bool]
    created_at: NotRequired[datetime]
    description: NotRequired[str]
    r"""truncated to first 1000 characters"""
    head_branch: NotRequired[str]
    labels: NotRequired[List[str]]
    r"""List of github labels"""
    requested_reviewers: NotRequired[List[str]]
    r"""List of github handles"""
    status: NotRequired[str]
    title: NotRequired[str]


class PullRequestMetadata(BaseModel):
    r"""This can only be populated when the github app is installed for a repo"""

    base_branch: Optional[str] = None

    can_merge: Optional[bool] = None

    created_at: Optional[datetime] = None

    description: Optional[str] = None
    r"""truncated to first 1000 characters"""

    head_branch: Optional[str] = None

    labels: Optional[List[str]] = None
    r"""List of github labels"""

    requested_reviewers: Optional[List[str]] = None
    r"""List of github handles"""

    status: Optional[str] = None

    title: Optional[str] = None


class GithubPublishingPRResponseTypedDict(TypedDict):
    r"""Open generation PRs pending publishing"""

    pending_version: NotRequired[str]
    pull_request: NotRequired[str]
    pull_request_metadata: NotRequired[PullRequestMetadataTypedDict]
    r"""This can only be populated when the github app is installed for a repo"""


class GithubPublishingPRResponse(BaseModel):
    r"""Open generation PRs pending publishing"""

    pending_version: Optional[str] = None

    pull_request: Optional[str] = None

    pull_request_metadata: Optional[PullRequestMetadata] = None
    r"""This can only be populated when the github app is installed for a repo"""
