"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .remotesourcesubscriptionsettings import (
    RemoteSourceSubscriptionSettings,
    RemoteSourceSubscriptionSettingsTypedDict,
)
from .revisioncontentsmetadata import (
    RevisionContentsMetadata,
    RevisionContentsMetadataTypedDict,
)
from datetime import datetime
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CompositeSpecMetadataTypedDict(TypedDict):
    subscription_id: str
    r"""The subscription ID for the remote source subscription, if applicable. This indicates that the namespace is created by a remote source and thus is composite."""
    subscription_settings: RemoteSourceSubscriptionSettingsTypedDict


class CompositeSpecMetadata(BaseModel):
    subscription_id: str
    r"""The subscription ID for the remote source subscription, if applicable. This indicates that the namespace is created by a remote source and thus is composite."""

    subscription_settings: RemoteSourceSubscriptionSettings


class NamespaceTypedDict(TypedDict):
    r"""A namespace contains many revisions."""

    created_at: datetime
    id: str
    r"""{organization_slug}/{workspace_slug}/{namespace_name}"""
    name: str
    r"""A human-readable name for the namespace."""
    updated_at: datetime
    archived_at: NotRequired[datetime]
    composite_spec_metadata: NotRequired[CompositeSpecMetadataTypedDict]
    latest_revision_metadata: NotRequired[RevisionContentsMetadataTypedDict]
    public: NotRequired[bool]
    r"""Indicates whether the namespace is publicly accessible"""


class Namespace(BaseModel):
    r"""A namespace contains many revisions."""

    created_at: datetime

    id: str
    r"""{organization_slug}/{workspace_slug}/{namespace_name}"""

    name: str
    r"""A human-readable name for the namespace."""

    updated_at: datetime

    archived_at: Optional[datetime] = None

    composite_spec_metadata: Optional[CompositeSpecMetadata] = None

    latest_revision_metadata: Optional[RevisionContentsMetadata] = None

    public: Optional[bool] = None
    r"""Indicates whether the namespace is publicly accessible"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "archived_at",
                "composite_spec_metadata",
                "latest_revision_metadata",
                "public",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
