"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TargetResource(str, Enum):
    DOCUMENT = "document"


class PublishingTokenTypedDict(TypedDict):
    r"""A token used to publish to a target"""

    created_at: datetime
    created_by: str
    id: str
    organization_id: str
    target_id: str
    target_resource: TargetResource
    token: str
    token_name: str
    valid_until: datetime
    workspace_id: str
    updated_at: NotRequired[datetime]
    updated_by: NotRequired[str]


class PublishingToken(BaseModel):
    r"""A token used to publish to a target"""

    created_at: datetime

    created_by: str

    id: str

    organization_id: str

    target_id: str

    target_resource: TargetResource

    token: str

    token_name: str

    valid_until: datetime

    workspace_id: str

    updated_at: Optional[datetime] = None

    updated_by: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["updated_at", "updated_by"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
