"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventtype import EventType
from .subscriptiontype import SubscriptionType
from datetime import datetime
from speakeasy_client_sdk_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RegistrySubscriptionTypedDict(TypedDict):
    r"""A subscription to a registry event"""

    created_at: datetime
    event_type: EventType
    id: str
    namespace_name: str
    subscription_settings: str
    subscription_type: SubscriptionType
    updated_at: datetime
    workspace_id: str
    deleted_at: NotRequired[datetime]
    tags: NotRequired[List[str]]


class RegistrySubscription(BaseModel):
    r"""A subscription to a registry event"""

    created_at: datetime

    event_type: EventType

    id: str

    namespace_name: str

    subscription_settings: str

    subscription_type: SubscriptionType

    updated_at: datetime

    workspace_id: str

    deleted_at: Optional[datetime] = None

    tags: Optional[List[str]] = None
