"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .remotedocument import RemoteDocument, RemoteDocumentTypedDict
from speakeasy_client_sdk_python.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RemoteSourceTypedDict(TypedDict):
    r"""Remote source configuration"""

    inputs: List[RemoteDocumentTypedDict]
    output: RemoteDocumentTypedDict
    r"""A document hosted in the registry"""
    overlays: NotRequired[List[RemoteDocumentTypedDict]]


class RemoteSource(BaseModel):
    r"""Remote source configuration"""

    inputs: List[RemoteDocument]

    output: RemoteDocument
    r"""A document hosted in the registry"""

    overlays: Optional[List[RemoteDocument]] = None
