"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from speakeasy_client_sdk_python.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class RevisionContentsMetadataType(str, Enum):
    OPENAPI_BUNDLE = "OPENAPI_BUNDLE"
    OPENAPI_OVERLAY = "OPENAPI_OVERLAY"


class RevisionContentsMetadataTypedDict(TypedDict):
    contains_code_samples: bool
    r"""Whether the OAS contains code samples."""
    created_at: datetime
    description: str
    r"""The OAS description"""
    hash: str
    r"""The hash of the contents"""
    namespace: str
    r"""The fully qualified namespace"""
    num_overlay_actions: int
    r"""The number of overlay actions in the OAS. Will be 0 if the OAS is not an overlay."""
    operation_ids: List[str]
    r"""The operation IDs contained in the OAS. Will be empty if the OAS is an overlay."""
    revision_digest: str
    r"""The digest of the parent bundle"""
    tags: List[str]
    r"""The tags contained in the OAS -- NOT the OCI tags. Will be empty if the OAS is an overlay."""
    title: str
    r"""The OAS title"""
    type: RevisionContentsMetadataType
    version: str
    r"""The OAS version"""
    workspace_id: str
    r"""The workspace ID"""


class RevisionContentsMetadata(BaseModel):
    contains_code_samples: bool
    r"""Whether the OAS contains code samples."""

    created_at: datetime

    description: str
    r"""The OAS description"""

    hash: str
    r"""The hash of the contents"""

    namespace: str
    r"""The fully qualified namespace"""

    num_overlay_actions: int
    r"""The number of overlay actions in the OAS. Will be 0 if the OAS is not an overlay."""

    operation_ids: List[str]
    r"""The operation IDs contained in the OAS. Will be empty if the OAS is an overlay."""

    revision_digest: str
    r"""The digest of the parent bundle"""

    tags: List[str]
    r"""The tags contained in the OAS -- NOT the OCI tags. Will be empty if the OAS is an overlay."""

    title: str
    r"""The OAS title"""

    type: RevisionContentsMetadataType

    version: str
    r"""The OAS version"""

    workspace_id: str
    r"""The workspace ID"""
