"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .diagnostic import Diagnostic, DiagnosticTypedDict
from enum import Enum
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SuggestionType(str, Enum):
    METHOD_NAMES = "method-names"
    DIAGNOSTICS_ONLY = "diagnostics-only"


class SuggestOptsOldTypedDict(TypedDict):
    suggestion_type: SuggestionType
    diagnostics: NotRequired[List[DiagnosticTypedDict]]


class SuggestOptsOld(BaseModel):
    suggestion_type: SuggestionType

    diagnostics: Optional[List[Diagnostic]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["diagnostics"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
