"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_client_sdk_python.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class AuthTypedDict(TypedDict):
    header: str
    secret: str
    

class Auth(BaseModel):
    header: str
    secret: str
    

class WorkflowDocumentTypedDict(TypedDict):
    r"""A document referenced by a workflow"""
    
    location: str
    auth: NotRequired[AuthTypedDict]
    

class WorkflowDocument(BaseModel):
    r"""A document referenced by a workflow"""
    
    location: str
    auth: Optional[Auth] = None
    
