"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_client_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WorkspaceSettingsTypedDict(TypedDict):
    workspace_id: str
    webhook_url: NotRequired[str]


class WorkspaceSettings(BaseModel):
    workspace_id: str

    webhook_url: Optional[str] = None
