"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from speakeasy_client_sdk_python.models.shared import (
    registrysubscription as shared_registrysubscription,
)
from speakeasy_client_sdk_python.types import BaseModel
from speakeasy_client_sdk_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSubscriptionGlobalsTypedDict(TypedDict):
    workspace_id: NotRequired[str]


class CreateSubscriptionGlobals(BaseModel):
    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None


class CreateSubscriptionRequestTypedDict(TypedDict):
    registry_subscription: shared_registrysubscription.RegistrySubscriptionTypedDict
    r"""The subscription to create"""
    workspace_id: NotRequired[str]
    r"""The workspace ID"""


class CreateSubscriptionRequest(BaseModel):
    registry_subscription: Annotated[
        shared_registrysubscription.RegistrySubscription,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The subscription to create"""

    workspace_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""The workspace ID"""


class CreateSubscriptionResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    registry_subscription: NotRequired[
        shared_registrysubscription.RegistrySubscriptionTypedDict
    ]
    r"""OK"""


class CreateSubscriptionResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    registry_subscription: Optional[
        shared_registrysubscription.RegistrySubscription
    ] = None
    r"""OK"""
