"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
import pydantic
from pydantic import model_serializer
from speakeasy_client_sdk_python.models.shared import (
    schemastoreitem as shared_schemastoreitem,
)
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Format(str, Enum):
    r"""The format of the OpenAPI specification."""

    JSON = "json"
    YAML = "yaml"


class CreateSchemaStoreItemRequestBodyTypedDict(TypedDict):
    format_: Format
    r"""The format of the OpenAPI specification."""
    package_name: str
    r"""The package name to use in code snippets / quickstart."""
    sdk_classname: str
    r"""The classname of the SDK to use in code snippets / quickstart."""
    spec: str
    r"""The OpenAPI specification to store."""


class CreateSchemaStoreItemRequestBody(BaseModel):
    format_: Annotated[Format, pydantic.Field(alias="format")]
    r"""The format of the OpenAPI specification."""

    package_name: Annotated[str, pydantic.Field(alias="packageName")]
    r"""The package name to use in code snippets / quickstart."""

    sdk_classname: Annotated[str, pydantic.Field(alias="sdkClassname")]
    r"""The classname of the SDK to use in code snippets / quickstart."""

    spec: str
    r"""The OpenAPI specification to store."""


class CreateSchemaStoreItemResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    schema_store_item: NotRequired[shared_schemastoreitem.SchemaStoreItemTypedDict]
    r"""OK"""


class CreateSchemaStoreItemResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    schema_store_item: Optional[shared_schemastoreitem.SchemaStoreItem] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["SchemaStoreItem"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateSchemaStoreItemRequestBody.model_rebuild()
except NameError:
    pass
