"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from pydantic import field_serializer
from speakeasy_client_sdk_python.models import shared
from speakeasy_client_sdk_python.models.shared import (
    billingaddon as shared_billingaddon,
)
from speakeasy_client_sdk_python.types import BaseModel
from speakeasy_client_sdk_python.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteBillingAddOnRequestTypedDict(TypedDict):
    add_on: shared_billingaddon.BillingAddOn
    r"""The specific add-on to delete."""


class DeleteBillingAddOnRequest(BaseModel):
    add_on: Annotated[
        shared_billingaddon.BillingAddOn,
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The specific add-on to delete."""

    @field_serializer("add_on")
    def serialize_add_on(self, value):
        if isinstance(value, str):
            try:
                return shared.BillingAddOn(value)
            except ValueError:
                return value
        return value


class DeleteBillingAddOnResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class DeleteBillingAddOnResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
