"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from speakeasy_client_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GenerateCodeSamplePreviewResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    two_hundred_application_json_response_stream: NotRequired[httpx.Response]
    r"""Successfully returned codeSample overlay file"""
    two_hundred_application_x_yaml_response_stream: NotRequired[httpx.Response]
    r"""Successfully returned codeSample overlay file"""


class GenerateCodeSamplePreviewResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    two_hundred_application_json_response_stream: Optional[httpx.Response] = None
    r"""Successfully returned codeSample overlay file"""

    two_hundred_application_x_yaml_response_stream: Optional[httpx.Response] = None
    r"""Successfully returned codeSample overlay file"""
