"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from speakeasy_client_sdk_python.models.shared import (
    codesamplesjobstatus as shared_codesamplesjobstatus,
)
from speakeasy_client_sdk_python.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GenerateCodeSamplePreviewAsyncResponseBodyTypedDict(TypedDict):
    r"""Job accepted, returns a job ID to poll for status and result"""

    job_id: str
    r"""The job ID for polling"""
    status: shared_codesamplesjobstatus.CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""


class GenerateCodeSamplePreviewAsyncResponseBody(BaseModel):
    r"""Job accepted, returns a job ID to poll for status and result"""

    job_id: str
    r"""The job ID for polling"""

    status: shared_codesamplesjobstatus.CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""


class GenerateCodeSamplePreviewAsyncResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[GenerateCodeSamplePreviewAsyncResponseBodyTypedDict]
    r"""Job accepted, returns a job ID to poll for status and result"""


class GenerateCodeSamplePreviewAsyncResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[GenerateCodeSamplePreviewAsyncResponseBody] = None
    r"""Job accepted, returns a job ID to poll for status and result"""
