"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
import pydantic
from pydantic import model_serializer
from speakeasy_client_sdk_python.models.shared import (
    codesamplesjobstatus as shared_codesamplesjobstatus,
    usagesnippets as shared_usagesnippets,
)
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from speakeasy_client_sdk_python.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCodeSamplePreviewAsyncRequestTypedDict(TypedDict):
    job_id: str
    r"""The ID of the job to check the status and retrieve results"""


class GetCodeSamplePreviewAsyncRequest(BaseModel):
    job_id: Annotated[
        str,
        pydantic.Field(alias="jobID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The ID of the job to check the status and retrieve results"""


class GetCodeSamplePreviewAsyncResponseBodyTypedDict(TypedDict):
    r"""Job is still in progress"""

    status: shared_codesamplesjobstatus.CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""


class GetCodeSamplePreviewAsyncResponseBody(BaseModel):
    r"""Job is still in progress"""

    status: shared_codesamplesjobstatus.CodeSamplesJobStatus
    r"""The current status of the job. Possible values are `pending` or `running`."""


class GetCodeSamplePreviewAsyncResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    usage_snippets: NotRequired[shared_usagesnippets.UsageSnippetsTypedDict]
    r"""OK"""
    object: NotRequired[GetCodeSamplePreviewAsyncResponseBodyTypedDict]
    r"""Job is still in progress"""


class GetCodeSamplePreviewAsyncResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    usage_snippets: Optional[shared_usagesnippets.UsageSnippets] = None
    r"""OK"""

    object: Optional[GetCodeSamplePreviewAsyncResponseBody] = None
    r"""Job is still in progress"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["UsageSnippets", "object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
