"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import httpx
import pydantic
from pydantic import model_serializer
from speakeasy_client_sdk_python.types import BaseModel, UNSET_SENTINEL
from speakeasy_client_sdk_python.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPublishingTokenPublicMetadataRequestTypedDict(TypedDict):
    token_id: str
    r"""Unique identifier of the publishing token."""


class GetPublishingTokenPublicMetadataRequest(BaseModel):
    token_id: Annotated[
        str,
        pydantic.Field(alias="tokenID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the publishing token."""


class GetPublishingTokenPublicMetadataResponseBodyTypedDict(TypedDict):
    r"""OK"""

    organization_id: NotRequired[str]
    target_id: NotRequired[str]
    target_resource: NotRequired[str]
    valid_until: NotRequired[datetime]
    workspace_id: NotRequired[str]


class GetPublishingTokenPublicMetadataResponseBody(BaseModel):
    r"""OK"""

    organization_id: Optional[str] = None

    target_id: Optional[str] = None

    target_resource: Optional[str] = None

    valid_until: Optional[datetime] = None

    workspace_id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "organization_id",
                "target_id",
                "target_resource",
                "valid_until",
                "workspace_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetPublishingTokenPublicMetadataResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[GetPublishingTokenPublicMetadataResponseBodyTypedDict]
    r"""OK"""


class GetPublishingTokenPublicMetadataResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[GetPublishingTokenPublicMetadataResponseBody] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
