"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
import pydantic
from speakeasy_client_sdk_python.models.shared import (
    publishingtoken as shared_publishingtoken,
)
from speakeasy_client_sdk_python.types import BaseModel
from speakeasy_client_sdk_python.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPublishingTokenByIDRequestTypedDict(TypedDict):
    token_id: str
    r"""Unique identifier of the publishing token."""


class GetPublishingTokenByIDRequest(BaseModel):
    token_id: Annotated[
        str,
        pydantic.Field(alias="tokenID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the publishing token."""


class GetPublishingTokenByIDResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    publishing_token: NotRequired[shared_publishingtoken.PublishingTokenTypedDict]
    r"""OK"""


class GetPublishingTokenByIDResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    publishing_token: Optional[shared_publishingtoken.PublishingToken] = None
    r"""OK"""
