"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from speakeasy_client_sdk_python.models.shared import workspace as shared_workspace
from speakeasy_client_sdk_python.types import BaseModel
from speakeasy_client_sdk_python.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateWorkspaceDetailsRequestTypedDict(TypedDict):
    workspace_id: str
    r"""Unique identifier of the workspace."""
    workspace: shared_workspace.WorkspaceTypedDict
    r"""The workspace details to update."""


class UpdateWorkspaceDetailsRequest(BaseModel):
    workspace_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the workspace."""

    workspace: Annotated[
        shared_workspace.Workspace,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The workspace details to update."""


class UpdateWorkspaceDetailsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class UpdateWorkspaceDetailsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
