workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    speakeasy-openapi:
        inputs:
            - location: https://speakeasy.com/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/speakeasy-openapi
targets:
    speakeasy-client-sdk-python:
        target: python
        source: speakeasy-openapi
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-python-speakeasy-client-sdk-python
